spring:
  application:
    name: user-provider

dubbo:
  protocol:
    name: dubbo
    port: 12345
#  registry:
#    address: zookeeper://172.16.87.26:2181
#    timeout: 60000
  registries:
    r1:
#      id: r1-id
      address: zookeeper://172.16.87.26:2181
      timeout: 60000
#      isDefault: false
      register: false
    r2:
#      id: r2-id
      address: zookeeper://172.16.87.28:2181
      timeout: 60000
#      isDefault: true
      register: true


